language: rust
sudo: false
addons:
  apt:
    packages:
    - libgpg-error-dev
    - libgpgme11
    - gpgv
    - libgpgme11-dev
    - libgpg-error0
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
    - rust: beta